spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/local
    username: user
    password: pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop